Revert of Add work-around to symlink.gni to avoid "not up-to-date" ninja errors (patchset #1 id:1 of https://codereview.chromium.org/2344243002/ )
Reason for revert:
Breaks iOS build with failure:

FAILED: gen/linked_src/third_party/objective_c/google_toolbox_for_mac
python ../../build/symlink.py --update-target-mtimes -f ../../../../../../third_party/google_toolbox_for_mac/src gen/linked_src/third_party/objective_c/google_toolbox_for_mac
Traceback (most recent call last):
  File "../../build/symlink.py", line 65, in <module>
    sys.exit(Main(sys.argv))
  File "../../build/symlink.py", line 56, in Main
    os.utime(s, None)
OSError: [Errno 2] No such file or directory: '../../../../../../third_party/google_toolbox_for_mac/src'

Original issue's description:
> Add work-around to symlink.gni to avoid "not up-to-date" ninja errors
>
> Ninja bug: https://github.com/ninja-build/ninja/issues/1186
>
> BUG=646165
>
> Committed: https://crrev.com/80f464d5151c3eec102604faf5fa36d9369b64aa
> Cr-Commit-Position: refs/heads/master@{#419751}

TBR=dpranke@chromium.org,agrieve@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=646165

Review-Url: https://codereview.chromium.org/2356973002
Cr-Commit-Position: refs/heads/master@{#419871}


CrOS-Libchrome-Original-Commit: 65f3a42b24088c3a96de9becbe96c4a0094ca843