media capture, mojo: Sprinkle noexcept in a few more classes
Commit fc5fe70812c ("FrameSinkVideoCapture clean-up: Remove unused APIs,
style fixes") added the noexcept marker to FrameSinkVideoCapture's
ConsumptionState inner class.

This breaks the GCC build due to the fact that its members' types do not
have noexcept themselves:

    ../../content/browser/media/capture/frame_sink_video_capture_device.cc: At global scope:
    ../../content/browser/media/capture/frame_sink_video_capture_device.cc:372:1: error: function ‘content::FrameSinkVideoCaptureDevice::ConsumptionState::ConsumptionState(content::FrameSinkVideoCaptureDevice::ConsumptionState&&)’ defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ‘’
    FrameSinkVideoCaptureDevice::ConsumptionState::ConsumptionState(

clang is fine because we pass -fno-exceptions and it disables the same error
there, while GCC continues to raise it (bug 843143 and its corresponding CL
have a longer discussion on this issue).

In this case, mark CursorRendererUndoer as well as mojo's ubiquitous
InterfacePtr with noexcept to fix the build.

Bug: 754872, 819294, 843143
Change-Id: I78714fda26d21e0979aed4fe26d543463dff9631
Reviewed-on: https://chromium-review.googlesource.com/1107918
Reviewed-by: Ken Rockot <rockot@chromium.org>
Reviewed-by: Sergey Ulanov <sergeyu@chromium.org>
Commit-Queue: Raphael Kubo da Costa (CET) <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#569029}

CrOS-Libchrome-Original-Commit: a7d6d9872e267e3e970707e394e84092177b357d