Remove base::internal::InotifyReader's destructor.
InotifyReader is instantiated as a base::LazyInstance::Leaky object,
which is never properly destroyed, since commit 18c0fac7d ("Make
InotifyReader a leaky lazy instance").

Having a destructor that is never called causes build issues with GCC
6.1.1, so we can just remove it altogether:

  ../../base/files/file_path_watcher_linux.cc:276:1: error: 'base::{anonymous}::InotifyReader::~InotifyReader()' defined but not used [-Werror=unused-function]

While here, also remove all code related to |shutdown_pipe_| since it
was only used in conjunction with ~InotifyReader().

R=dcheng@chromium.org,mnissler@chromium.org,danakj@chromium.org,thestig@chromium.org
BUG=636346

Review-Url: https://codereview.chromium.org/2236523002
Cr-Commit-Position: refs/heads/master@{#411294}


CrOS-Libchrome-Original-Commit: 983625d272c1b35a6297dd02c51fd1ee0fce3230