Revert 169327 - Fix histogram printing for Telemetry tests.
This appears to break Chrome for Android perf tests, in addition to
the kraken benchmark upstream.

-------------------
Log output:
Traceback (most recent call last):
  File "clank/build/run_crossbrowser_perftests.py", line 1429, in <module>
    sys.exit(main(sys.argv))

  File "clank/build/run_crossbrowser_perftests.py", line 1416, in main
    passed &= chrome_benchmarks.Run()

  File "/usr/local/google/b/build/slave/soju-official-perf-noflash-clankium/build/src/clank/build/../../build/android/pylib/base_test_runner.py", line 79, in Run
    return self.RunTests()

  File "clank/build/run_crossbrowser_perftests.py", line 329, in RunTests
    return self.RunCrossBrowserPerfTests(options.filter, options.force_disabled)

  File "clank/build/run_crossbrowser_perftests.py", line 379, in RunCrossBrowserPerfTests
    passed &= bool(RunTheTest())

  File "clank/build/run_crossbrowser_perftests.py", line 368, in RunTheTest
    return test_fn()

  File "clank/build/run_crossbrowser_perftests.py", line 1222, in PaintBlankBenchmark
    timeout)

  File "clank/build/run_crossbrowser_perftests.py", line 426, in RunPaintBenchmarkHelper
    timeout=timeout))

  File "/usr/local/google/b/build/slave/soju-official-perf-noflash-clankium/build/src/clank/build/perf_test_runner.py", line 629, in RunPerfTest
    result, units, result_type=result_type)

  File "/usr/local/google/b/build/slave/soju-official-perf-noflash-clankium/build/src/clank/build/../../build/android/pylib/perf_tests_helper.py", line 127, in PrintPerfResult
    output += '\nAvg %s: %f%s' % (measurement, avg, units)

  TypeError: float argument required, not str

-------------------
OriGinal commit:
The previous version was printing out only the first histogram.

BUG=

Review URL: https://codereview.chromium.org/11413144

TBR=marja@chromium.org
Review URL: https://codereview.chromium.org/11418165

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@169510 0039d316-1c4b-4281-b951-d872f2087c98


CrOS-Libchrome-OriGinal-Commit: 930633b198cf64a5d8af1881602ca83799c80dc7