Assert that md5sum was built instead of failing silently.
The exit when md5sum does not exist fails silently with a short message buried
in the output with no tests run. The reason is because this is an asynchronous
process and the exit does not exist the script. The assert on the other hand
will stop the script and print the following, making it clear the script failed
and that md5sum should be built:

@@@STEP_FAILURE@@@
Traceback (most recent call last):
  File "build/android/run_instrumentation_tests.py", line 108, in <module>
    sys.exit(main(sys.argv))
  File "build/android/run_instrumentation_tests.py", line 101, in main
    ret = DispatchInstrumentationTests(options)
  ...
    results_lists = async_results.get(999999)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 528, in get
    raise self._value
AssertionError: Please build md5sum.

BUG=


Review URL: https://chromiumcodereview.appspot.com/11613014

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@174299 0039d316-1c4b-4281-b951-d872f2087c98


CrOS-Libchrome-OriGinal-Commit: 69657d364ace8c5c26017fee2c3f915cd31408a2