Revert of base: Introduce an explicit call for reducing emulated discardable memory usage. (https://codereview.chromium.org/448173002/)
Reason for revert:
tree-closer content_browsertests failing on Linux Chromium OS ASan LSan Tests (1)
test RenderThreadImplBrowserTest.EmulatedDiscardableMemoryDiscardedWhenWidgetsHidden
failing since
http://build.chromium.org/p/chromium.memory/builders/Linux%20Chromium%20OS%20ASan%20LSan%20Tests%20%281%29/builds/2501

Error: LeakSanitizer: detected memory leaks (Various Indirect leaks).
..
SUMMARY: AddressSanitizer: 19178 byte(s) leaked in 34 allocation(s).

Original issue's description:
> base: Introduce an explicit call for reducing emulated discardable memory usage.
>     
> This removes the use of memory pressure signals from discardable memory
> system and instead introduces an explicit call for reducing emulated
> discardable memory that the renderer can call when all widgets are hidden
> until we have a better mechanism in place.
>     
> BUG=398087
> TEST=base_unittests,content_browsertests
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=288793

TBR=jochen@chromium.org,mark@chromium.org,reveman@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=398087

Review URL: https://codereview.chromium.org/458343003

Cr-Commit-Position: refs/heads/master@{#288913}
git-svn-id: svn://svn.chromium.org/chrome/trunk/src@288913 0039d316-1c4b-4281-b951-d872f2087c98


CrOS-Libchrome-Original-Commit: 309237963b8ebc55ebc118fc9e7c3c18b662e205