Revert 227604 "Simple shell that loads a dll and calls an entryp..."
This broke compile on a couple bots:
http://build.chromium.org/p/chromium.webkit/builders/Linux%20Tests%20%28dbg%29/builds/202/
http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Linux%20x64/builds/44976

../../mojo/shell/app_container.cc: In function 'void mojo::shell::LaunchAppOnThread(const base::FilePath&, mojo::Handle)':
../../mojo/shell/app_container.cc:43:1:error: jump to label 'completed' [-fpermissive]
../../mojo/shell/app_container.cc:33:10:error:   from here [-fpermissive]
../../mojo/shell/app_container.cc:36:14:error:   crosses initialization of 'MojoResult result'
../../mojo/shell/app_container.cc:43:1:error: jump to label 'completed' [-fpermissive]
../../mojo/shell/app_container.cc:25:10:error:   from here [-fpermissive]
../../mojo/shell/app_container.cc:36:14:error:   crosses initialization of 'MojoResult result'
../../mojo/shell/app_container.cc:28:20:error:   crosses initialization of 'MojoResult (* main_function)(mojo::Handle)'

> Simple shell that loads a dll and calls an entrypoint function passing in a handle to a pipe created by the shell app.
> 
> To achieve this I had to make mojo_system a <(component) so sample_app.dll could link against it. Trung, Darin tells me you had a different idea about how to achieve this. Consider this CL a starting point for the discussion :-)
> 
> R=darin@chromium.org
> BUG=
> 
> Review URL: https://codereview.chromium.org/25895002

TBR=ben@chromium.org

Review URL: https://codereview.chromium.org/26344004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@227607 0039d316-1c4b-4281-b951-d872f2087c98


CrOS-Libchrome-OriGinal-Commit: 299e52c635938ef25b599e240f960b48f18415d5