Revert "Fix compiler warnings in libchrome"
This reverts commit b636ff6a8ac3b54b3067289f01848252ab71eceb.

This broke trunk with messages like:

In file included from external/libchrome/base/time/time_posix.cc:29:0:
external/libchrome/base/lazy_instance.h:51:36: error: missing initializer for member 'base::LazyInstance<base::Lock, base::internal::LeakyLazyInstanceTraits<base::Lock> >::private_instance_' [-Werror=missing-field-initializers]
 #Defenderine LAZY_INSTANCE_INITIALIZER {}
                                    ^
external/libchrome/base/time/time_posix.cc:39:38: note: in expansion of macro 'LAZY_INSTANCE_INITIALIZER'
     g_sys_time_to_time_struct_lock = LAZY_INSTANCE_INITIALIZER;
                                      ^
external/libchrome/base/lazy_instance.h:51:36: error: missing initializer for member 'base::LazyInstance<base::Lock, base::internal::LeakyLazyInstanceTraits<base::Lock> >::private_buf_' [-Werror=missing-field-initializers]
 #Defenderine LAZY_INSTANCE_INITIALIZER {}
                                    ^
external/libchrome/base/time/time_posix.cc:39:38: note: in expansion of macro 'LAZY_INSTANCE_INITIALIZER'
     g_sys_time_to_time_struct_lock = LAZY_INSTANCE_INITIALIZER;
                                      ^
cc1plus: all warnings being treated as errors

Change-Id: I0c0308e716bd1ed7914e2a032e439a9261d38e56