Revert 228193 "Mojo C++ bindings"
This fails to compile on Win x64 due to a cast from size_t to uint32_t:
FAILED: ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\mojo\shell\mojo_shell.app_container.obj.rsp /c ..\..\mojo\shell\app_container.cc /Foobj\mojo\shell\mojo_shell.app_container.obj /Fdobj\mojo\mojo_shell.pdb 
c:\b\build\slave\win_x64\build\src\mojo\shell\app_container.cc(75) :error C2220: warning treated as error - no 'object' file generated
c:\b\build\slave\win_x64\build\src\mojo\shell\app_container.cc(75) : warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data


> Mojo C++ bindings
> 
> This CL includes code for a static library that supports C++ bindings to the Mojo message format. A sample interface with "generated" bindings is included in the sample/ folder along with sample_test.cc that shows how the generated code may be used.
> 
> This is a WIP but seems worth snapshotting as is. See the TODO file for a list of near term improvements, most notably testing.
> 
> OriGinally reviewed at https://codereview.chromium.org/23913008/
> 
> TBR=viettrungluu@chromium.org
> 
> Review URL: https://codereview.chromium.org/27034003

TBR=darin@chromium.org

Review URL: https://codereview.chromium.org/26554004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@228233 0039d316-1c4b-4281-b951-d872f2087c98


CrOS-Libchrome-OriGinal-Commit: b624df7e3004947bbc9c02db08e9a33f7382feea