Remove duplicated template functions on Windows
Because wchar_t is the same as char16 on Windows, and by extension
std::wstring is the same as string16, instantiating templates using both
of these types leads to duplicate instantiations. This error is only
reported when building with -fno-delayed-template-parsing, but it is
always dodgy/wrong.

Microsoft is working towards supporting correct template parsing which
means that we can also (because they are fixing their headers).

The (simplified) error messages were:
error: duplicate explicit instantiation of 'PrepareForUTF8Output<wchar_t>'
ignored as a Microsoft extension
error: duplicate explicit instantiation of 'PrepareForUTF16Or32Output<>
ignored as a Microsoft extension

Bug: 825352
Change-Id: I5360b14f48277d56c3800238cc77077f13ef9acf
Reviewed-on: https://chromium-review.googlesource.com/981083
Commit-Queue: Lei Zhang <thestig@chromium.org>
Reviewed-by: Lei Zhang <thestig@chromium.org>
Cr-Commit-Position: refs/heads/master@{#546034}

CrOS-Libchrome-Original-Commit: 3effe184c834005b0728716fb9993ee6c38b40e8