Revert of Adds the ability for the renderer to create the mojo channel (https://codereview.chromium.org/195993010/)
Reason for revert:
Broke linux bot:

FAILED: c++ -Wl,-z,now -Wl,-z,relro -pthread -Wl,-z,noexecstack -fPIC -L. -Wl,-uIsHeapProfilerRunning,-uProfilerStart -Wl,-u_Z21InitialMallocHook_NewPKvj,-u_Z22InitialMallocHook_MMapPKvS0_jiiix,-u_Z22InitialMallocHook_SbrkPKvi -Wl,-u_Z21InitialMallocHook_NewPKvm,-u_Z22InitialMallocHook_MMapPKvS0_miiil,-u_Z22InitialMallocHook_SbrkPKvl -Wl,-u_ZN15HeapLeakChecker12IgnoreObjectEPKv,-u_ZN15HeapLeakChecker14UnIgnoreObjectEPKv -m32 -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -Wl,-rpath=\$ORIGin/lib/ -Wl,-rpath-link=lib/ -o content_perftests -Wl,--start-group obj/content/browser/renderer_host/input/content_perftests.input_router_impl_perftest.o obj/content/common/content_perftests.cc_messages_perftest.o obj/content/test/content_perftests.run_all_perftests.o obj/content/libcontent_browser.a obj/content/libcontent_common.a obj/content/libtest_support_content.a obj/base/libtest_support_base.a obj/cc/libcc.a obj/testing/libgtest.a obj/testing/perf/libperf_test.a obj/ui/gfx/libgfx.a obj/ui/gfx/libgfx_geometry.a obj/base/libbase.a obj/base/libbase_static.a obj/base/allocator/liballocator_extension_thunks.a obj/third_party/modp_b64/libmodp_b64.a obj/base/third_party/dynamic_annotations/libdynamic_annotations.a obj/base/libsymbolize.a obj/base/libxdg_mime.a obj/third_party/libevent/libevent.a obj/components/libtracing.a obj/ipc/libipc.a obj/net/libnet.a obj/base/libbase_i18n.a obj/third_party/icu/libicui18n.a obj/third_party/icu/libicuuc.a obj/third_party/icu/libicudata.a obj/crypto/libcrcrypto.a obj/net/third_party/nss/libcrssl.a obj/sdch/libsdch.a obj/third_party/zlib/libchrome_zlib.a obj/url/liburl_lib.a obj/build/linux/libgio.a obj/skia/libskia_library.a obj/skia/libskia_opts.a obj/skia/libskia_opts_ssse3.a obj/third_party/sfntly/libsfntly.a obj/skia/libskia_chrome.a obj/skia/libskia_chrome_opts.a obj/third_party/libjingle/libjingle.a obj/third_party/libjingle/libjingle_p2p_constants.a obj/ui/accessibility/libaccessibility.a obj/third_party/libpng/libpng.a obj/third_party/libjpeg_turbo/libjpeg_turbo.a obj/ui/accessibility/libax_gen.a obj/tools/json_schema_compiler/libapi_gen_util.a obj/ui/base/libui_base.a obj/ui/events/libevents_base.a obj/ui/events/libdom4_keycode_converter.a obj/ui/events/libevents.a obj/ui/shell_dialogs/libshell_dialogs.a obj/ui/aura/libaura.a obj/gpu/libcommand_buffer_client.a obj/gpu/libcommand_buffer_common.a obj/gpu/command_buffer/libgles2_utils.a obj/gpu/libcommand_buffer_service.a obj/gpu/libdisk_cache_proto.a obj/third_party/protobuf/libprotobuf_lite.a obj/third_party/re2/libre2.a obj/third_party/smhasher/libcityhash.a obj/ui/gl/libgl_wrapper.a obj/third_party/angle/src/libtranslator.a obj/third_party/angle/src/libpreprocessor.a obj/gpu/libgles2_cmd_helper.a obj/gpu/libgpu_config.a obj/build/linux/libpci.a obj/third_party/libXNVCtrl/libXNVCtrl.a obj/gpu/libgpu_ipc.a obj/ui/compositor/libcompositor.a obj/media/libmedia.a obj/third_party/opus/libopus.a obj/media/libshared_memory_support.a obj/media/libshared_memory_support_sse.a obj/third_party/ffmpeg/libffmpeg.a obj/third_party/libvpx/libvpx.a obj/third_party/libvpx/libvpx_asm_offsets_vp8.a obj/third_party/libvpx/libvpx_intrinsics_mmx.a obj/third_party/libvpx/libvpx_intrinsics_sse2.a obj/third_party/libvpx/libvpx_intrinsics_ssse3.a obj/media/libmedia_asm.a obj/media/libmedia_mmx.a obj/media/libmedia_sse.a obj/media/libmedia_sse2.a obj/gpu/libgles2_c_lib.a obj/gpu/libgles2_implementation.a obj/gpu/skia_bindings/libgpu_skia_bindings.a obj/third_party/WebKit/Source/platform/libblink_platform.a obj/third_party/WebKit/Source/wtf/libwtf.a obj/third_party/WebKit/Source/platform/libblink_common.a obj/third_party/libwebp/libwebp_dec.a obj/third_party/libwebp/libwebp_dsp.a obj/third_party/libwebp/libwebp_utils.a obj/third_party/libwebp/libwebp_demux.a obj/third_party/libwebp/libwebp_enc.a obj/third_party/ots/libots.a obj/third_party/brotli/libbrotli.a obj/third_party/qcms/libqcms.a obj/v8/tools/gyp/libv8_base.ia32.a obj/v8/tools/gyp/libv8_snapshot.a obj/third_party/iccjpeg/libiccjpeg.a obj/third_party/harfbuzz-ng/libharfbuzz-ng.a obj/third_party/WebKit/Source/web/libblink_web.a obj/third_party/WebKit/Source/core/libwebcore_dom.a obj/third_party/WebKit/Source/heap/libblink_heap.a obj/third_party/WebKit/Source/heap/libblink_heap_asm_stubs.a obj/third_party/libxml/libxml2.a obj/third_party/libxslt/libxslt.a obj/third_party/sqlite/libsqlite3.a obj/third_party/WebKit/Source/core/libwebcore_html.a obj/third_party/WebKit/Source/core/libwebcore_remaining.a obj/third_party/WebKit/Source/core/libwebcore_rendering.a obj/third_party/WebKit/Source/core/libwebcore_svg.a obj/third_party/WebKit/Source/core/libwebcore_generated.a obj/Gin/libGin.a obj/third_party/WebKit/Source/modules/libmodules.a obj/webkit/common/gpu/libwebkit_gpu.a obj/webkit/common/libwebkit_common.a obj/webkit/libwebkit_storage_browser.a obj/sql/libsql.a obj/third_party/leveldatabase/libleveldatabase.a obj/third_party/snappy/libsnappy.a obj/webkit/libwebkit_storage_common.a obj/mojo/libmojo_environment_chromium.a obj/mojo/libmojo_environment_chromium_impl.a obj/mojo/libmojo_common_lib.a obj/mojo/libmojo_system_impl.a obj/ppapi/libppapi_shared.a obj/ui/Surface/libSurface.a obj/google_apis/libgoogle_apis.a obj/third_party/zlib/google/libzip.a obj/third_party/zlib/libminizip.a obj/ui/events/libgesture_detection.a obj/ui/snapshot/libsnapshot.a obj/content/browser/speech/proto/libspeech_proto.a obj/net/libhttp_server.a obj/printing/libprinting.a obj/sandbox/libsandbox_services.a obj/sandbox/libsuid_sandbox_client.a obj/sandbox/libseccomp_bpf.a obj/sandbox/libseccomp_bpf_helpers.a libyuv.a obj/jingle/libjingle_glue.a obj/third_party/webrtc/modules/libdesktop_capture.a obj/third_party/webrtc/system_wrappers/source/libsystem_wrappers.a obj/third_party/webrtc/modules/libdesktop_capture_differ_sse2.a obj/sandbox/libc_urandom_override.a obj/ppapi/libppapi_ipc.a obj/third_party/flac/libflac.a obj/third_party/speex/libspeex.a obj/dbus/libdbus.a obj/net/libnet_test_support.a obj/testing/libgmock.a obj/net/tools/tld_cleanup/libtld_cleanup_util.a obj/base/allocator/liballocator.a obj/net/libnet_with_v8.a obj/ui/events/libevents_test_support.a obj/ui/gfx/libgfx_test_support.a obj/content/libcontent_app_both.a obj/content/libcontent_child.a obj/webkit/child/libwebkit_child.a obj/ui/native_theme/libnative_theme.a obj/content/libcontent_gpu.a obj/content/libcontent_ppapi_pluGin.a obj/content/libcontent_renderer.a obj/webkit/renderer/compositor_bindings/libwebkit_compositor_bindings.a obj/webkit/renderer/compositor_bindings/libwebkit_compositor_support.a obj/mojo/libmojo_js_bindings_lib.a obj/third_party/libjingle/libjingle_webrtc.a obj/third_party/libjingle/libjingle_webrtc_common.a obj/third_party/libsrtp/libsrtp.a obj/third_party/webrtc/modules/libmedia_file.a obj/third_party/webrtc/modules/libvideo_capture_module.a obj/third_party/webrtc/modules/libwebrtc_utility.a obj/third_party/webrtc/modules/libaudio_coding_module.a obj/third_party/webrtc/modules/libCNG.a obj/third_party/webrtc/common_audio/libcommon_audio.a obj/third_party/webrtc/common_audio/libcommon_audio_sse2.a obj/third_party/webrtc/modules/libG711.a obj/third_party/webrtc/modules/libG722.a obj/third_party/webrtc/modules/libiLBC.a obj/third_party/webrtc/modules/lPaytonAC.a obj/third_party/webrtc/modules/lPaytonACFix.a obj/third_party/webrtc/modules/libPCM16B.a obj/third_party/webrtc/modules/libNetEq.a obj/third_party/webrtc/modules/libwebrtc_opus.a obj/third_party/webrtc/modules/libacm2.a obj/third_party/webrtc/modules/libNetEq4.a obj/third_party/webrtc/modules/libwebrtc_video_coding.a obj/third_party/webrtc/modules/libwebrtc_i420.a obj/third_party/webrtc/common_video/libcommon_video.a obj/third_party/webrtc/modules/video_coding/utility/libvideo_coding_utility.a obj/third_party/webrtc/modules/video_coding/codecs/vp8/libwebrtc_vp8.a obj/third_party/webrtc/modules/libvideo_render_module.a obj/third_party/usrsctp/libusrsctplib.a obj/third_party/libjingle/libpeerconnection.a obj/third_party/webrtc/video_enGine/libvideo_enGine_core.a obj/third_party/webrtc/modules/librtp_rtcp.a obj/third_party/webrtc/modules/libpaced_sender.a obj/third_party/webrtc/modules/libremote_bitrate_estimator.a obj/third_party/webrtc/modules/remote_bitrate_estimator/librbe_components.a obj/third_party/webrtc/modules/libbitrate_controller.a obj/third_party/webrtc/modules/libvideo_processing.a obj/third_party/webrtc/modules/libvideo_processing_sse2.a obj/third_party/webrtc/voice_enGine/libvoice_enGine.a obj/third_party/webrtc/modules/libaudio_conference_mixer.a obj/third_party/webrtc/modules/libaudio_processing.a obj/third_party/webrtc/modules/libaudioproc_debug_proto.a obj/third_party/webrtc/modules/libaudio_processing_sse2.a obj/third_party/webrtc/modules/libaudio_device.a obj/ppapi/libppapi_host.a obj/ppapi/libppapi_proxy.a obj/content/libcontent_utility.a obj/content/libcontent_worker.a obj/cc/libcc_test_support.a obj/gpu/libgpu_unittest_utils.a obj/ui/gl/libgl_unittest_utils.a obj/ppapi/libppapi_unittest_shared.a obj/ipc/libtest_support_ipc.a obj/ui/aura/libaura_test_support.a obj/ui/compositor/libcompositor_test_support.a obj/ui/libui_test_support.a lib/libmojo_system.so -Wl,--end-group -lrt -ldl -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lX11 -lXi -lXrandr -lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -lgconf-2 -lgio-2.0 -lresolv -lfontconfig -lfreetype -lpangocairo-1.0 -lcairo -lpangoft2-1.0 -lpango-1.0 -lexpat -lXcursor -lXext -lXfixes -lXrender -lXcomposite -lasound -lXdamage -lXtst -lcups -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lgnutls -lgcrypt -lz -lpthread -lcrypt -lm -L/lib/i386-linux-gnu -lcap -ludev -ldbus-1
obj/content/common/mojo/content_common.mojo_channel_init.o: In function `content::MojoChannelInit::Init(int, scoped_refptr<base::TaskRunner>)':
mojo_channel_init.cc:(.text._ZN7content15MojoChannelInit4InitEi13scoped_refptrIN4base10TaskRunnerEE+0x230): undefined reference to `MojoClose'
obj/content/common/mojo/content_common.mojo_channel_init.o: In function `content::MojoChannelInit::~MojoChannelInit()':
mojo_channel_init.cc:(.text._ZN7content15MojoChannelInitD2Ev+0x124): undefined reference to `MojoClose'
mojo_channel_init.cc:(.text._ZN7content15MojoChannelInitD2Ev+0x134): undefined reference to `MojoClose'
obj/mojo/system/embedder/mojo_system_impl.embedder.o: In function `mojo::embedder::Init()':
embedder.cc:(.text._ZN4mojo8embedder4InitEv+0x30): undefined reference to `mojo::Core::Init(mojo::Core*)'
obj/mojo/system/embedder/mojo_system_impl.embedder.o: In function `mojo::embedder::CreateChannel(mojo::embedder::ScopedPlatformHandle, scoped_refptr<base::TaskRunner>, base::Callback<void (mojo::embedder::ChannelInfo*)>)':
embedder.cc:(.text._ZN4mojo8embedder13CreateChannelENS0_20ScopedPlatformHandleE13scoped_refptrIN4base10TaskRunnerEENS3_8CallbackIFvPNS0_11ChannelInfoEEEE+0x29): undefined reference to `mojo::Core::Get()'
obj/mojo/system/mojo_system_impl.core_impl.o: In function `mojo::system::CoreImpl::~CoreImpl()':
core_impl.cc:(.text._ZN4mojo6system8CoreImplD2Ev+0x4b): undefined reference to `mojo::Core::~Core()'
collect2: ld returned 1 exit status
ninja: build stopped: subcommand failed.

http://build.chromium.org/p/chromium/builders/Linux/builds/48261/steps/compile/logs/stdio

OriGinal issue's description:
> Adds the ability for the renderer to create the mojo channel
> 
> This is initiated and owned by RenderProcessHost. I've added a
> method to RenderProcessHostImpl to create the channel. No one is
> calling it yet, that will come after this.
> 
> RenderProcessHostImpl::CreateMojoChannel initiates the connection and
> sends an IPC message to the renderer. The renderer than creates its
> end of the connection.
> 
> End to end test will come once I've added all the pieces.
> 
> BUG=none
> TEST=none
> R=darin@chromium.org, tsepez@chromium.org, viettrungluu@chromium.org
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=257342

TBR=darin@chromium.org,tsepez@chromium.org,viettrungluu@chromium.org,sky@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=none

Review URL: https://codereview.chromium.org/201283002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@257346 0039d316-1c4b-4281-b951-d872f2087c98


CrOS-Libchrome-OriGinal-Commit: 14c9994aef35c3daf7bdd20f00d1f064dab27