Revert of Make landmines work on local builds too (patchset #3 of https://codereview.chromium.org/457003004/)
Reason for revert:
Apparently this requires win_toolchain.json to exist, but I'm not sure how it's supposed to get there (as seen on a clobber build):


Traceback (most recent call last):
  File "src/build/landmines.py", line 132, in <module>
    sys.exit(main())
  File "src/build/landmines.py", line 119, in main
    gyp_environment.SetEnvironment()
  File "C:\b\build\slave\win_trunk\build\src\build\gyp_environment.py", line 33, in SetEnvironment
    vs_toolchain.SetEnvironmentAndGetRuntimeDllDirs()
  File "C:\b\build\slave\win_trunk\build\src\build\vs_toolchain.py", line 33, in SetEnvironmentAndGetRuntimeDllDirs
    with open(json_data_file, 'r') as tempf:
IOError: [Errno 2] No such file or directory: 'C:\\b\\build\\slave\\win_trunk\\build\\src\\build\\win_toolchain.json'

OriGinal issue's description:
> Make landmines work on local builds too
> 
> Moves (some of) gyp environment setup out of gyp_chromium into separate
> module, and shares that between gyp_chromium and landmines.py.
> 
> landmines.py is added as the first entry in DEPS hooks so that it can
> clobber the entire build directory before running other hooks that
> extract/generate into the build dir.
> 
> R=iannucci@chromium.org
> BUG=400011
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=289099

TBR=scottmg@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=400011

Review URL: https://codereview.chromium.org/469623002

Cr-Commit-Position: refs/heads/master@{#289158}
git-svn-id: svn://svn.chromium.org/chrome/trunk/src@289158 0039d316-1c4b-4281-b951-d872f2087c98


CrOS-Libchrome-OriGinal-Commit: 5a9e71778a0357194e33d27c9802a6979dddbe4d